version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test
    volumes:
      - pg_vol:/var/lib/postgresql/data
    networks:
      - some_net

volumes:
  pg_vol:

networks:
  some_net:
    name: example_name