project:
  type: website
  output-dir: docs
  resources:
    - layout/html_files/some_video.webm

website:
  title: "Knowledge"
  sidebar:
    collapse-level: 1
    contents:
      - section: "Machine learning"
        contents:
          - machine_learning/gradient_descent.ipynb
          - machine_learning/models_selection_methods/l2_regularisation.ipynb
          - machine_learning/data_transformations/tf_idf.ipynb
          - section: "Metrics"
            contents:
            - machine_learning/metrics/CAP.ipynb
            - machine_learning/metrics/GINI.ipynb
            - machine_learning/metrics/jaccard_index.ipynb
      - section: "Python"
        contents:
        - section: "Basic"
          contents:
            - section: "Operators"
              contents:
                - python/basics/operators/arithmetic.ipynb
                - python/basics/operators/break.ipynb
                - python/basics/operators/in.ipynb
                - python/basics/operators/indexing.ipynb
                - python/basics/operators/order.ipynb
                - python/basics/operators/yield.ipynb
            - section: "Data types"
              contents:
                - python/basics/basic_datatypes/set.ipynb
                - python/basics/basic_datatypes/dict.ipynb
                - python/basics/basic_datatypes/str.ipynb
                - python/basics/basic_datatypes/frozenset.ipynb
                - python/basics/basic_datatypes/tuple.ipynb
                - python/basics/basic_datatypes/list.ipynb
            - section: "Path settings"
              contents:
                - python/basics/paths_settings/pythonpath.ipynb
                - python/basics/paths_settings/pathlib.ipynb
            - python/basics/functions.ipynb
            - python/basics/exceptions.ipynb
            - python/basics/packages.ipynb
            - python/basics/virtual_environment.ipynb
            - python/basics/logging.ipynb
            - section: "CLI arguments"
              contents:
                - python/basics/cli_arguments/argparse.ipynb
                - python/basics/cli_arguments/manually.ipynb
        - section: "Advanced"
          contents:
            - python/advanced/collections.ipynb
            - python/advanced/excel_export.ipynb
            - python/advanced/ipython_magics.ipynb
            - python/advanced/jinja.ipynb
            - python/advanced/multi_threads.ipynb
            - python/advanced/transformers.ipynb
            - python/advanced/hashlib.ipynb
            - section: "Airflow"
              contents:
                - python/advanced/airflow/run_airflow.ipynb
                - python/advanced/airflow/tutorial_dag.ipynb
            - section: "Geopy"
              contents:
                - python/advanced/geopy/distances.ipynb
                - python/advanced/geopy/request.ipynb
            - section: "unittest"
              contents:
                - python/advanced/unittest/check_error.ipynb
                - python/advanced/unittest/run_before_after.ipynb
                - python/advanced/unittest/mocking.ipynb
            - section: "Build package"
              contents:
                - python/advanced/build_package/basics.ipynb
                - python/advanced/build_package/uploading_to_pypi.ipynb
                - python/advanced/build_package/dependencies.ipynb
        - section: "Pandas"
          contents:
            - section: "Data types"
              contents: 
                - python/pandas/data_types/datetime.ipynb
                - python/pandas/data_types/columns_by_types.ipynb
            - python/pandas/loc.ipynb
            - python/pandas/groupby.ipynb
            - python/pandas/data_visualisation.ipynb
            - python/pandas/inline_columns_add.ipynb
            - python/pandas/read_sql.ipynb
        - section: "Sklearn"
          contents:
            - python/sklearn/pipeline.ipynb
            - python/sklearn/columns_transformer.ipynb
            - python/sklearn/grid_search_cv.ipynb
            - python/sklearn/frozen_steps.ipynb
            - python/sklearn/estimator_to_transformer.ipynb
            - python/sklearn/saving_models.ipynb
        - section: "Torch"
          contents:
            - section: "Tensor"
              contents:
                - python/torch/tensor/basic.ipynb
                - python/torch/tensor/element_wise.ipynb
            - python/torch/differentiation.ipynb
            - python/torch/layers.ipynb
            - python/torch/nn_module.ipynb
            - python/torch/regression_network.ipynb
            - python/torch/logistic_regression.ipynb
            - python/torch/multiclass_task.ipynb
            - python/torch/texts_classification.ipynb
            - section: "Computer vision"
              contents:
                - python/torch/vision/basic.ipynb
                - python/torch/vision/augmentations.ipynb
                - python/torch/vision/mnist.ipynb
                - python/torch/vision/pretrains.ipynb
                - python/torch/vision/cnn_classification.ipynb
                - python/torch/vision/unet.ipynb
                - python/torch/vision/datasets.ipynb
        - section: "Plotly"
          contents:
            - python/plotly/hovers.ipynb
            - python/plotly/dragmode.ipynb
            - python/plotly/color_from_scheme.ipynb
        - section: "Dash"
          contents:
            - python/dash/callbacks.ipynb
            - python/dash/components.ipynb
            - python/dash/select_clear_all.ipynb
            - python/dash/multipage_applications.ipynb
            - python/dash/empty_figure.ipynb
        - section: "Fastapi"
          contents:
            - python/fastapi/run_application.ipynb
            - python/fastapi/pass_arguments.ipynb
            - python/fastapi/return_json.ipynb
        - section: "SQLAlchemy"
          contents:
            - python/sqlalchemy/create_table.ipynb
            - python/sqlalchemy/query.ipynb
            - python/sqlalchemy/add_record.ipynb
            - python/sqlalchemy/relations.ipynb
      - section: "Math"
        contents:
          - math/basics.ipynb
          - math/conditional_probability.ipynb
          - math/cent_limit_theorem.ipynb
          - math/maximum_likelihood.ipynb
          - math/latex.ipynb
          - section: "Stat testing"
            contents:
              - math/stat_testing/idea.ipynb
              - math/stat_testing/binomial_test.ipynb
      - section: "Algorithms"
        contents:
          - algorithms/complexity.ipynb
          - algorithms/trees.ipynb
          - algorithms/dynamic_prog.ipynb
          - algorithms/quick_sort.ipynb
          - section: "Specific tasks"
            contents:
              - algorithms/specific_tasks/emergency_task.ipynb
              - algorithms/specific_tasks/sinking_islands.ipynb
      - section: "Docker"
        contents:
          - Docker/sources.ipynb
          - Docker/docker_commands.ipynb
          - Docker/docker_file_instructions.ipynb
          - Docker/image_creation.ipynb
          - Docker/docker_volumes.ipynb
          - Docker/logs.ipynb
          - section: "Network"
            contents:
              - Docker/network/ports.ipynb
              - Docker/network/container_connection.ipynb
              - Docker/network/default_networks.ipynb
              - Docker/network/container_communication.ipynb
              - Docker/network/local_network.ipynb
              - Docker/network/small_features.ipynb
      - section: "Git"
        contents:
          - git/init.ipynb
          - git/file_stages.ipynb
          - git/commit.ipynb
          - git/diff.ipynb
          - git/checkout.ipynb
          - git/branches.ipynb
          - git/log.ipynb
          - git/merge.ipynb
          - git/previous_commit.ipynb
          - git/ignore.ipynb
      - section: "SQL"
        contents:
          - sql/build_container.ipynb
          - section: "SELECT"
            contents:
              - sql/select/join.ipynb
              - sql/select/sorting.ipynb
              - sql/select/unique_values.ipynb
              - sql/select/fill_empty.ipynb
              - section: "Aggregations (GROUP BY)"
                contents:
                  - sql/select/aggregation/functions.ipynb
                  - sql/select/aggregation/conditions_on_aggregats.ipynb
                  - sql/select/aggregation/conditions_in_aggregats.ipynb
              - sql/select/expand_array.ipynb
              - sql/select/NULL_conditions.ipynb
              - sql/select/first_last_value.ipynb
              - sql/select/conditional.ipynb
          - section: "Date and time"
            contents:
              - sql/datetime/date_components.ipynb
              - sql/datetime/add_period.ipynb
          - sql/load_tables.ipynb
          - sql/json_datatype.ipynb
          - sql/special_cases.ipynb
          - section: "Python interaction"
            contents:
              - sql/python_interaction/python_from_container.ipynb
              - sql/python_interaction/python_on_host.ipynb
              - sql/python_interaction/create_database.ipynb
      - section: "Layout"
        contents:
          - layout/sources.ipynb
          - section: "HTML"
            contents:
            - layout/html/other.ipynb
            - layout/html/tables.ipynb
            - layout/html/lists.ipynb
          - section: "CSS"
            contents:
            - layout/css/other.ipynb
            - layout/css/style_application.ipynb
            - layout/css/margin.ipynb
            - layout/css/padding.ipynb
            - layout/css/overflow.ipynb
            - layout/css/elements_positions.ipynb
          - layout/forms.ipynb
      - section: "Other"
        contents:
          - other/linux_backup.ipynb
          - other/python_apache.ipynb
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
