project:
  type: website
  output-dir: docs
  resources:
    - layout/html_files/some_video.webm

website:
  title: "Knowledge"
  sidebar:
    contents:
      - section: "Docker"
        contents:
          - Docker/sources.ipynb
          - Docker/docker_commands.ipynb
          - Docker/docker_file_instructions.ipynb
          - Docker/image_creation.ipynb
          - Docker/docker_volumes.ipynb
          - Docker/logs.ipynb
          - Docker/postgres.ipynb
      - section: "Python"
        contents:
          - python/virtual_environment.ipynb
          - python/excel_export.ipynb
          - python/exceptions.ipynb
          - python/logging.ipynb
          - python/multi_threads.ipynb
      - section: "Layout"
        contents:
          - layout/sources.ipynb
          - layout/html.ipynb
          - layout/css.ipynb
          - layout/forms.ipynb
      - section: "Git"
        contents:
          - git/git_ignore.ipynb
      - section: "Dash"
        contents:
          - dash/callbacks.ipynb
          - dash/components.ipynb
          - dash/select_all.ipynb
      - section: "Other"
        contents:
          - other/linux_backup.ipynb
          - other/python_apache.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true