project:
  type: website
  output-dir: docs
  resources:
    - layout/html_files/some_video.webm

website:
  title: "Knowledge"
  sidebar:
    contents:
      - section: "Docker"
        contents:
          - Docker/sources.ipynb
          - Docker/docker_commands.ipynb
          - Docker/docker_file_instructions.ipynb
          - Docker/image_creation.ipynb
          - Docker/docker_volumes.ipynb
          - Docker/logs.ipynb
      - section: "Python"
        contents:
        - section: "Basic"
          contents:
            - section: "Data types"
              contents:
                - python/basics/basic_datatypes/set.ipynb
                - python/basics/basic_datatypes/dict.ipynb
                - python/basics/basic_datatypes/str.ipynb
                - python/basics/basic_datatypes/frozenset.ipynb
                - python/basics/basic_datatypes/tuple.ipynb
                - python/basics/basic_datatypes/list.ipynb
            - python/basics/operators.ipynb
            - python/basics/functions.ipynb
            - python/basics/exceptions.ipynb
            - python/basics/packages.ipynb
            - python/basics/virtual_environment.ipynb
            - python/basics/collections.ipynb
            - python/basics/excel_export.ipynb
            - python/basics/logging.ipynb
            - python/basics/multi_threads.ipynb
            - python/basics/ipython_magics.ipynb
        - section: "Pandas"
          contents:
            - python/pandas/groupby.ipynb
            - python/pandas/database_interaciton.ipynb
      - section: "Layout"
        contents:
          - layout/sources.ipynb
          - layout/html.ipynb
          - layout/css.ipynb
          - layout/forms.ipynb
      - section: "Git"
        contents:
          - git/git_ignore.ipynb
      - section: "Dash"
        contents:
          - dash/callbacks.ipynb
          - dash/components.ipynb
          - dash/select_clear_all.ipynb
      - section: "Other"
        contents:
          - other/linux_backup.ipynb
          - other/python_apache.ipynb
      - section: "Postgres"
        contents:
          - postgres/build_container.ipynb
          - postgres/basic_sql_operations.ipynb
          - postgres/load_tables.ipynb
          - postgres/python_interaction.ipynb
          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true