project:
  type: website
  output-dir: docs

website:
  title: "Knowledge bank"
  sidebar:
    contents:
      - section: "Docker"
        contents:
          - Docker/sources.ipynb
          - Docker/image.ipynb
          - Docker/containers.ipynb
          - Docker/image_creation.ipynb
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true