services:
  base:
    image: knowledge:latest
    build:
      context: ./
      dockerfile: ./dockerfiles/dockerfile
    volumes:
      - ./:/knowledge
    ports:
      - 8888:8888
    command: ["jupyter", "lab", "--ip", "0.0.0.0", "--allow-root", "--notebook-dir=/knowledge"]
  did:
    image: did_knowledge:latest
    build:
      context: ./
      dockerfile: ./dockerfiles/did/dockerfile
    volumes:
      - ./:/knowledge
    ports:
      - 8888:8888
    privileged: True
    command: ["--notebook-dir=/knowledge"]
