[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "src"
version = "0.0.0"
dependencies = [
    "typeguard==4.4.2",
    "clickhouse_connect==0.8.17",
    "psycopg==3.2.6"
]

[tool.hatch.build.targets.wheel]
packages = ["src"]