version: "3"

services:
  exmap_im:
    container_name: test_cont
    image: ubuntu
    volumes:
      - ${PWD}/test_file:/test_file1
      - ./test_file:/test_file2
    tty: true
    stdin_open: true