# version: "3"

# services:
#   some_service:
#     image: ubuntu

# volumes:
#   pg_vol:
#     name: some_name

version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test

volumes:
  pg_vol:
  named_vol: 
    name: some_name