version: "3"

services:
  # тут сравниваю как работают два контейнера
  # в смысле инструкции healthcheck
  db1:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "docker_app"]
  db2:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test

  # тут цепляю два левых контейнера
  # для которых сравниваю два контейнера,
  # которые завязы вокруг healthy предыдущих
  ubuntu1:
    image: ubuntu
    depends_on:
      db1:
        condition: service_healthy
    tty: true
    stdin_open: true
  ubuntu2:
    image: ubuntu
    depends_on:
      db2:
        condition: service_healthy
    tty: true
    stdin_open: true

  # а тут еще два которые зависят от того
  # подняты ли предыдущие
  ubuntu3:
    image: ubuntu
    depends_on:
      ubuntu1:
        condition: service_started
    tty: true
    stdin_open: true
  ubuntu4:
    image: ubuntu
    depends_on:
      ubuntu2:
        condition: service_started
    tty: true
    stdin_open: true
  
