FROM ghcr.io/fedorkobak/jlb:latest

WORKDIR /knowledge_setup

COPY ./src ./src
COPY ./pyproject.toml ./pyproject.toml

RUN pip install \
    bash_kernel \
    -e . && \
    python3 -m bash_kernel.install
