FROM python:3.12.8-slim

COPY ./src /src
COPY ./pyproject.toml /pyproject.toml

RUN apt update && apt install -y jq git
RUN pip install \
    bash_kernel \
    "jupyter_lab_build @ git+https://github.com/fedorkobak/jupyter_lab_build.git" \
    -e . && \
    python3 -m bash_kernel.install

CMD ["jupyter", "lab", "--ip", "0.0.0.0", "--allow-root"]
