version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test
    volumes:
      - ex_vol:/var/lib/postgresql/data
    networks:
      - ex_net

volumes:
  ex_vol:
networks:
  ex_net: