project:
  type: website
  output-dir: docs
  resources:
    - layout/html_files/some_video.webm

website:
  title: "Knowledge"
  sidebar:
    collapse-level: 1
    contents:
      - section: "Machine learning"
        contents:
          - machine_learning/models_selection_methods/l2_regularisation.ipynb
          - machine_learning/data_transformations/tf_idf.ipynb
          - section: "Metrics"
            contents:
            - machine_learning/metrics/CAP.ipynb
            - machine_learning/metrics/GINI.ipynb
      - section: "Python"
        contents:
        - section: "Basic"
          contents:
            - section: "Data types"
              contents:
                - python/basics/basic_datatypes/set.ipynb
                - python/basics/basic_datatypes/dict.ipynb
                - python/basics/basic_datatypes/str.ipynb
                - python/basics/basic_datatypes/frozenset.ipynb
                - python/basics/basic_datatypes/tuple.ipynb
                - python/basics/basic_datatypes/list.ipynb
            - section: "Path settings"
              contents:
                - python/basics/paths_settings/pythonpath.ipynb
                - python/basics/paths_settings/pathlib.ipynb
            - python/basics/operators.ipynb
            - python/basics/functions.ipynb
            - python/basics/exceptions.ipynb
            - python/basics/packages.ipynb
            - python/basics/virtual_environment.ipynb
            - python/basics/collections.ipynb
            - python/basics/excel_export.ipynb
            - python/basics/logging.ipynb
            - python/basics/multi_threads.ipynb
            - python/basics/ipython_magics.ipynb
        - section: "Pandas"
          contents:
            - python/pandas/loc.ipynb
            - python/pandas/groupby.ipynb
            - python/pandas/datetime.ipynb
            - python/pandas/data_visualisation.ipynb
            - python/pandas/read_sql.ipynb
        - section: "Sklearn"
          contents:
            - python/sklearn/pipeline.ipynb
        - section: "Plotly"
          contents:
            - python/plotly/hovers.ipynb
            - python/plotly/dragmode.ipynb
            - python/plotly/color_from_scheme.ipynb
        - section: "Dash"
          contents:
            - python/dash/callbacks.ipynb
            - python/dash/components.ipynb
            - python/dash/select_clear_all.ipynb
            - python/dash/multipage_applications.ipynb
        - section: "Fastapi"
          contents:
            - python/fastapi/run_application.ipynb
            - python/fastapi/pass_arguments.ipynb
            - python/fastapi/return_json.ipynb
        - section: "SQLAlchemy"
          contents:
            - python/sqlalchemy/create_table.ipynb
            - python/sqlalchemy/query.ipynb
            - python/sqlalchemy/add_record.ipynb
            - python/sqlalchemy/relations.ipynb
        - section: "Airflow"
          contents:
            - python/airflow/run_airflow.ipynb
            - python/airflow/tutorial_dag.ipynb
        - section: "Geopy"
          contents:
            - python/geopy/distances.ipynb
            - python/geopy/request.ipynb
        - section: "Jinja2"
          contents:
            - python/jinja2/generate_html.ipynb
      - section: "Docker"
        contents:
          - Docker/sources.ipynb
          - Docker/docker_commands.ipynb
          - Docker/docker_file_instructions.ipynb
          - Docker/image_creation.ipynb
          - Docker/docker_volumes.ipynb
          - Docker/logs.ipynb
          - section: "Network"
            contents:
              - Docker/network/ports.ipynb
              - Docker/network/container_connection.ipynb
              - Docker/network/default_networks.ipynb
              - Docker/network/container_communication.ipynb
              - Docker/network/local_network.ipynb
              - Docker/network/small_features.ipynb
      - section: "Git"
        contents:
          - git/init.ipynb
          - git/file_stages.ipynb
          - git/commit.ipynb
          - git/diff.ipynb
          - git/checkout.ipynb
          - git/branches.ipynb
          - git/log.ipynb
          - git/merge.ipynb
          - git/previous_commit.ipynb
          - git/ignore.ipynb
      - section: "Postgres"
        contents:
          - postgres/build_container.ipynb
          - postgres/NULL_conditions.ipynb
          - postgres/conditions_on_agregats.ipynb
          - postgres/grouping.ipynb
          - postgres/unique_values.ipynb
          - postgres/join.ipynb
          - postgres/expand_array.ipynb
          - postgres/load_tables.ipynb
          - postgres/first_last_value.ipynb
          - postgres/json_datatype.ipynb
          - postgres/special_cases.ipynb
          - section: "Python interaction"
            contents:
              - postgres/python_interaction/python_from_container.ipynb
              - postgres/python_interaction/python_on_host.ipynb
              - postgres/python_interaction/create_database.ipynb
      - section: "Layout"
        contents:
          - layout/sources.ipynb
          - layout/html.ipynb
          - section: "CSS"
            contents:
            - layout/css/other.ipynb
            - layout/css/style_application.ipynb
            - layout/css/margin.ipynb
            - layout/css/padding.ipynb
            - layout/css/overflow.ipynb
          - layout/forms.ipynb
      - section: "Other"
        contents:
          - other/linux_backup.ipynb
          - other/python_apache.ipynb
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
